package cn.wbomb.wxshop.generate;

import cn.wbomb.wxshop.generate.Shop;
import cn.wbomb.wxshop.generate.ShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    long countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int insert(Shop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int insertSelective(Shop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int updateByExampleSelective(@Param("row") Shop row, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int updateByExample(@Param("row") Shop row, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int updateByPrimaryKeySelective(Shop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Jul 08 23:39:58 CST 2023
     */
    int updateByPrimaryKey(Shop row);
}