spring:
  application:
    name: wxshop-order
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop_order
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
dubbo:
  scan:
    base-packages: cn.wbomb.order.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181

wxshop:
  orderservice:
    version: 0.0.1
server:
  port: 8081

mybatis:
  config-location: classpath:db/mybatis/config.xml
